   services:
     api:
       ports: !override
         - "8658:8000"
       env_file: !override
         - stack.env
     worker:
       env_file: !override
         - stack.env
     email_worker:
       env_file: !override
         - stack.env
   volumes:
     miniodata:
       driver: local
       driver_opts:
         type: none
         o: bind
         device: /mnt/d/freeframe/minio
